/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package snake.ladder;

/**
 *
 * @author Ragiri Rajasehar
 */
public class about extends javax.swing.JFrame {

    /**
     * Creates new form help
     */
    public about() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        snow = new javax.swing.JLabel();
        snow1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dark Crystal", 3, 35)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 25, 25));
        jLabel2.setText("ABOUT");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 180, -1));

        jLabel4.setFont(new java.awt.Font("Final Frontier", 2, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(192, 126, 37));
        jLabel4.setText("Student of APIIIT RKValley, Dept of CSE");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 470, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/snake/ladder/rgukt.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 80, 70));

        jLabel10.setFont(new java.awt.Font("Final Frontier", 2, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(171, 132, 44));
        jLabel10.setText("Rajiv Gandhi University of Knowledge and Technologies");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 600, 40));

        jLabel13.setFont(new java.awt.Font("Final Frontier", 2, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(120, 93, 251));
        jLabel13.setText("\" RRS Creations can make Dreams as Real \".");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 480, 30));

        jLabel14.setFont(new java.awt.Font("Final Frontier", 2, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(185, 125, 11));
        jLabel14.setText("& Programming by ");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 210, 30));

        jLabel15.setFont(new java.awt.Font("Final Frontier", 2, 30)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(236, 164, 225));
        jLabel15.setText("Ragiri Rajasekhar");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 240, 40));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/snake/ladder/logohome.png"))); // NOI18N
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 90, 80));

        jLabel16.setFont(new java.awt.Font("Final Frontier", 2, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(185, 125, 11));
        jLabel16.setText("Game Designing , Motion effects");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 360, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/snake/ladder/Aboutbg.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 590));

        snow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/snake/ladder/giphy.gif"))); // NOI18N
        getContentPane().add(snow, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 510, 400));

        snow1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/snake/ladder/giphy.gif"))); // NOI18N
        getContentPane().add(snow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 250, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
       Home obj= new Home();
       this.setVisible(false);
       obj.setVisible(true);
       obj.setLocationRelativeTo(null);
       
    }//GEN-LAST:event_jLabel20MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(about.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(about.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(about.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(about.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new about().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel snow;
    private javax.swing.JLabel snow1;
    // End of variables declaration//GEN-END:variables
}
