/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package snake.ladder;

/**
 *
 * @author Ragiri Rajasehar
 */
public class help extends javax.swing.JFrame {

    /**
     * Creates new form help
     */
    public help() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dark Crystal", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 25, 25));
        jLabel2.setText("Help");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 150, -1));

        jLabel3.setFont(new java.awt.Font("Final Frontier", 2, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(120, 93, 251));
        jLabel3.setText("Progress bar");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 400, 140, 40));

        jLabel4.setFont(new java.awt.Font("Final Frontier", 2, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(254, 202, 202));
        jLabel4.setText("> Then the game is you the reach the goal quickly to win the game ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, -1));

        jLabel5.setFont(new java.awt.Font("Final Frontier", 2, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(254, 202, 202));
        jLabel5.setText("Goal quickly .");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 120, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/snake/ladder/CF.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, 150, 60));

        jLabel7.setFont(new java.awt.Font("Final Frontier", 2, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(254, 202, 202));
        jLabel7.setText("are placed at that number location.");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 290, 30));

        jLabel8.setFont(new java.awt.Font("Final Frontier", 2, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(254, 202, 202));
        jLabel8.setText("> Press and wait some time and Release the counter , then it show ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, 30));

        jLabel9.setFont(new java.awt.Font("Final Frontier", 2, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(254, 202, 202));
        jLabel9.setText("one Random number, at that number your selected super hero ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 540, 30));

        jLabel10.setFont(new java.awt.Font("Final Frontier", 2, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(254, 202, 202));
        jLabel10.setText("otherwise your opponent will reach the goal quickly they win the ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 570, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/snake/ladder/batman.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 270, 50, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/snake/ladder/ironman.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, 50, -1));

        jLabel13.setFont(new java.awt.Font("Final Frontier", 2, 22)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(120, 93, 251));
        jLabel13.setText("Counter");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, 80, 30));

        jLabel14.setFont(new java.awt.Font("Final Frontier", 2, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(254, 202, 202));
        jLabel14.setText("> Progress bar shows the game percentage how much you complete.");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, 30));

        jLabel15.setFont(new java.awt.Font("Final Frontier", 2, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(254, 202, 202));
        jLabel15.setText("game. ALL THE BEST lets begin the game.....");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 510, 40));

        jLabel16.setFont(new java.awt.Font("Final Frontier", 2, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(254, 202, 202));
        jLabel16.setText("you back the snake tail position . Also ladders are use to reach");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 560, 30));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/snake/ladder/progress.png"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 440, 190, 30));

        jLabel18.setFont(new java.awt.Font("Final Frontier", 2, 22)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(120, 93, 251));
        jLabel18.setText("Super Heros");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 240, 140, 30));

        jLabel19.setFont(new java.awt.Font("Final Frontier", 2, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(254, 202, 202));
        jLabel19.setText("> When we move toward the positions , snakes are bited you then ");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/snake/ladder/logohome.png"))); // NOI18N
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 90, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/snake/ladder/namedemo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
       Home obj= new Home();
       this.setVisible(false);
       obj.setVisible(true);
       obj.setLocationRelativeTo(null);
       
    }//GEN-LAST:event_jLabel20MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new help().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
