/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package snake.ladder;

/**
 *
 * @author Ragiri Rajasehar
 */
public class names extends javax.swing.JFrame {

    /**
     * Creates new form names
     */
    public names() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ir1 = new javax.swing.JLabel();
        snow = new javax.swing.JLabel();
        ir = new javax.swing.JLabel();
        snow1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tf1.setBackground(new java.awt.Color(0, 51, 51));
        tf1.setFont(new java.awt.Font("Final Frontier", 3, 24)); // NOI18N
        tf1.setForeground(new java.awt.Color(178, 167, 167));
        tf1.setToolTipText("Enter Player1 Name");
        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        getContentPane().add(tf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 230, 60));

        jLabel2.setFont(new java.awt.Font("Final Frontier", 3, 23)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(213, 213, 213));
        jLabel2.setText("Player1 Name :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("Final Frontier", 3, 23)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(213, 213, 213));
        jLabel3.setText("Player2 Name :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, -1, -1));

        tf2.setBackground(new java.awt.Color(0, 51, 51));
        tf2.setFont(new java.awt.Font("Final Frontier", 3, 24)); // NOI18N
        tf2.setForeground(new java.awt.Color(178, 167, 167));
        tf2.setToolTipText("Enter Player1 Name");
        tf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf2ActionPerformed(evt);
            }
        });
        getContentPane().add(tf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 230, 60));

        jButton1.setBackground(new java.awt.Color(46, 37, 37));
        jButton1.setFont(new java.awt.Font("Final Frontier", 3, 30)); // NOI18N
        jButton1.setForeground(new java.awt.Color(218, 209, 201));
        jButton1.setText("Start the Game !!!");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 310, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/snake/ladder/logohome.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 80, 80));

        ir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/snake/ladder/ironred.png"))); // NOI18N
        getContentPane().add(ir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 100, 230));

        snow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/snake/ladder/giphy.gif"))); // NOI18N
        getContentPane().add(snow, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 510, 400));

        ir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/snake/ladder/batmann.png"))); // NOI18N
        getContentPane().add(ir, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, 110, 200));

        snow1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/snake/ladder/giphy.gif"))); // NOI18N
        getContentPane().add(snow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 250, 400));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/snake/ladder/namedemo.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1ActionPerformed

    private void tf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String str1=tf1.getText();
        String str2= tf2.getText();
        
        Snakeboard obj= new Snakeboard();
        obj.pname1.setText(str1);
        obj.pname2.setText(str2);
        this.setVisible(false);
        obj.setVisible(true);
        obj.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        Home obj= new Home();
        this.setVisible(false);
        obj.setVisible(true);
        obj.setLocationRelativeTo(null);
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(names.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(names.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(names.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(names.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new names().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ir;
    private javax.swing.JLabel ir1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel snow;
    private javax.swing.JLabel snow1;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    // End of variables declaration//GEN-END:variables
}
